trigger:
- main

# variables set on azdevops to avoid circular dependency warning
# $(DEFAULT_BRANCH)
# $(MY_INDEX)
# $(BLOB_CONTAINER_NAME)
variables:
  AZURE_SUBSCRIPTION: $(PROD_AZURE_SUBSCRIPTION)
  STORAGE_ACCOUNT_NAME: $(PROD_STORAGE_ACCOUNT_NAME)
  PROFILE_CDN_NAME: $(PROD_PROFILE_CDN_NAME)
  ENDPOINT_NAME: $(PROD_ENDPOINT_NAME)
  RESOURCE_GROUP_NAME: $(PROD_RESOURCE_GROUP_NAME)
  BLOB_CONTAINER_NAME: $(PROD_BLOB_CONTAINER_NAME)
  AZURE_STORAGE_KEY: $(PROD_AZURE_STORAGE_KEY)
pool:
  vmImage: 'windows-2022'
stages:
  - stage: Deploy_PROD_assets_pagoPA
    jobs:
      - job: 'deploy'
        steps:
          # SYNC STORAGE 
          - task: AzureCLI@1
            displayName: 'Sync Storage'
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              scriptLocation: inlineScript
              inlineScript: |
                call az storage blob sync --container "$(BLOB_CONTAINER_NAME)" --account-name $(STORAGE_ACCOUNT_NAME) --account-key $(AZURE_STORAGE_KEY) -s "assets"
          # PURGE CDN AT EVERY COMMIT, so globally
          - task: AzureCLI@1
            displayName: 'Purge CDN'
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              scriptLocation: inlineScript
              inlineScript: |
                call az cdn endpoint purge -g $(RESOURCE_GROUP_NAME) -n $(ENDPOINT_NAME) --profile-name $(PROFILE_CDN_NAME) --content-paths "/*"
